name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs: 
  unit-tests-backend:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with: 
          go-version: "1.21"
          cache-dependency-path: bugtracker-backend/go.sum

      - name: install go-go-junit-report
        run: |
          go install github.com/jstemmer/go-junit-report/v2@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Execute Backend Unit Tests with Coverage
        working-directory: ./bugtracker-backend
        run: |
          go test -v -coverprofile=coverage.out ./... 2>&1 | go-junit-report > test-results.xml
          go tool cover -func=coverage.out > coverage.txt
          go tool cover -html=coverage.out -o coverage.html

      - name: Publish backend test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Backend Unit Test Report
          path: bugtracker-backend/test-results.xml
          reporter: jest-junit

      - name: Upload Backend Coverage Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: |
            bugtracker-backend/coverage.out
            bugtracker-backend/coverage.txt
            bugtracker-backend/coverage.html

      - name: Comment Backend Coverage Summary
        uses: marocchino/sticky-pull-request-comment@v2
        if: always()
        with:
          recreate: true
          header: backend-coverage
          message: |
            **Backend Code Coverage Summary**
            ```
            $(cat bugtracker-backend/coverage.txt)
            ```

  unit_tests-frontend:
    needs: unit-tests-backend
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4

      - name: Set up node.js
        uses: actions/setup-node@v4
        with: 
          node-version: "20"
          cache: "npm"
          cache-dependency-path: bugtracker-frontend/package-lock.json

      - name: Execute Frontend Unit Tests with Coverage
        working-directory: ./bugtracker-frontend
        run: |
          npm ci
          npm test -- --coverage --reporters=default --reporters=jest-junit

      - name: Publish Frontend Tests Result
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Frontend Unit Tests Report
          path: bugtracker-frontend/test-results.xml
          reporter: jest-junit

      - name: Upload Frontend Coverage Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: bugtracker-frontend/coverage

      - name: Comment Frontend Coverage Summary
        uses: marocchino/sticky-pull-request-comment@v2
        if: always()
        with:
          recreate: true
          header: frontend-coverage
          message: |
            **Frontend Code Coverage Summary**
            ```
            $(npx jest --coverage --coverageReporters=text-summary | tee /dev/tty)
            ```
